name: shellcheck
#name: 01_shellcheck.yml adding secondary checks

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # The pipeline should be executed every week automatically
    - cron:  '0 0 * * 0'
  push:
    # The pipeline should be executed from any branch

jobs:
  with-github-action:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        path: "pre_deploy.sh"
  with-downloaded-binary:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Download and run ShellCheck
      run: |
        scversion='v0.7.2';
        wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv;
        cp -f "shellcheck-${scversion}/shellcheck" /usr/local/bin
    - name: Run ShellCheck
      run: if shellcheck pre_deploy.sh; then echo "Successfully scanned pre_deploy.sh, no errors."; true; else false; fi # we have to pass false result to pipeline in case of fail
  with-apt-install:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Install ShellCheck
      run: sudo apt update
    - name: Install ShellCheck
      run: sudo apt install -y shellcheck
    - name: Run ShellCheck
      run: if shellcheck pre_deploy.sh; then echo "Successfully scanned pre_deploy.sh, no errors."; true; else false; fi # we have to pass false result to pipeline in case of fail
