name: 02_build_java.yml

on:
  push:
    branches:
    - main

jobs:
  building_java_app_manually:
    runs-on: ubuntu-22.04
    name: 
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install unzip curl zip -y
      - run: curl -s "https://get.sdkman.io" | bash
      - run: source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 11.0.16-zulu
      - run: source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install gradle 7.4
      - run: ./gradlew :spotlessApply
      - run: ./gradlew build
