name: 03_build_java.yml using gradle-build-action

on:
  push:
    branches:
    - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11.0.16
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
    - name: Run build of spotlessApply plugin with Gradle Wrapper
      run: ./gradlew :spotlessApply
    - name: Run build of project with Gradle Wrapper
      run: ./gradlew build
