name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
    - main

jobs:
  echo_a_sentence:
    runs-on: ubuntu-22.04
    name: build
    steps:
      - uses: actions/checkout@v2
      - run: echo 'It just works.'
