name: 04_build_java.yml and saving the build artifact and checking

on:
  push:
    branches:
    - main

jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11.0.16
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
    - name: Run build of spotlessApply plugin with Gradle Wrapper
      run: ./gradlew :spotlessApply
    - name: Run build of project with Gradle Wrapper
      run: ./gradlew build
#    - name: Create the zip file
#      run: zip ${{ secrets.ARTIFACT_NAME }}.zip build/libs/*.jar
    - name: Upload build result of this job
      uses: actions/upload-artifact@v3
      with:
        name: ${{ secrets.ARTIFACT_NAME }}
        path: build/libs/*.jar

  check-artifact-contents:
    needs: build-and-upload-artifact
    runs-on: ubuntu-22.04
    steps:
      - name: Download build result of previous job
        uses: actions/download-artifact@v3
        with:
          name: ${{ secrets.ARTIFACT_NAME }}
      - name: List all files after the artifact downloaded
        run: find
      - name: Check the contents of the artifact
        run: if [ "$(ls -1 *.jar | tee /dev/stderr | wc -l)" == "2" ]; then echo "OK."; true; else echo "Error."; false; fi
